image: node:6.9.5
services:
  - mongo:3.4.0

cache:
  paths:
  - node_modules/

before_script:
  - echo "before_script"
  - npm install

after_script:
  - echo "after_script"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - echo "before_script build"
  script:
    - echo "execute-script-for-build"
  after_script:
    - echo "after_script build"
  only:
    - feature/refactor-code
  tags:
    - aws ec2

test:
  stage: test
  before_script:
    - echo "before_script test"
    - npm install
  script:
    - echo "execute-script-for-test"
    - npm run test
  after_script:
    - echo "after_script test"
  only:
    - feature/refactor-code
  tags:
    - aws ec2

deploy:
  stage: deploy
  before_script:
    - echo "before_script deploy"
  script:
    - echo "execute-script-for-deploy"
  after_script:
    - echo "after_script deploy"
  only:
    - feature/refactor-code
  tags:
    - aws ec2
