/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const POST_TYPES = ['STATUS', 'EVENT'];

export const NOTIFY_TYPES = ['LIKES', 'COMMENTS', 'NEW_POST'];

export const PENDING = 'PENDING';
export const ACCEPTED = 'ACCEPTED';
export const REJECTED = 'REJECTED';
export const BLOCKED = 'BLOCKED';
export const NONE = 'NONE';

export const CONTROL_NEW_CONVERSATION = 'CONTROL_NEW_CONVERSATION';
export const ADD_USER_NEW_CONVERSATION = 'ADD_USER_NEW_CONVERSATION';
export const CHAT_SEND_MESSAGE = 'CHAT_SEND_MESSAGE';
export const CHAT_ON_MESSAGE_CHILD_ADD = 'CHAT_ON_MESSAGE_CHILD_ADD';
export const CHAT_LOAD_MESSAGE_HISTORY_SUCCESS = 'CHAT_LOAD_MESSAGE_HISTORY_SUCCESS';
export const CHAT_ON_CONVERSATION_CHILD_ADD = 'CHAT_ON_CONVERSATION_CHILD_ADD';
export const CHAT_LOAD_CONVERSATION_HISTORY_SUCCESS = 'CHAT_LOAD_CONVERSATION_HISTORY_SUCCESS';
export const CHAT_ACTIVE_CONVERSATION = 'CHAT_ACTIVE_CONVERSATION';
export const CHAT_ON_FAIL = 'CHAT_ON_FAIL';
