version: '2'
services:
  backend:
    image: registry.mttjsc.com/snsmobile/UserBackend:develop
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: api-sns.mttjsc.com
      VIRTUAL_PORT: '8081'
      LETSENCRYPT_HOST: api-sns.mttjsc.com
      LETSENCRYPT_EMAIL: cuong.nguyen@mttjsc.com
    expose:
      - '8081'
    labels:
      io.rancher.container.pull_image: always
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
    - /srv/sns/mongodb:/data/db
    expose:
    - '27017'
    command:
    - mongod
    - --smallfiles
    - --logpath=/dev/null
